# overlays/dev/deployment-patch.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
spec:
  # 개발 환경 배포 설정
  template:
    spec:
      containers:
        - name: pod-container
          # 개발 환경 변수 설정
          env:
            - name: CURRENT_ENV
              value: "dev"
          # 개발 환경 리소스 설정
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
