# application.yml (공통 설정)
spring:
  profiles:
    active: local
  application:
    name: cicd_demo

server:
  tomcat:
    apr:
      enabled:false

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    startup:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        startup:
          include: "*"
    prometheus:
      enabled: true  # 프로메테우스 엔드포인트 활성화
  metrics:
    enable:
      jvm: true
      process: true
      system: true
    tags:
      application: ${spring.application.name}  # 애플리케이션 이름을 태그로 추가