# EKS 클러스터 구성을 위한 eksctl 설정 파일
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # 클러스터 이름
  name: my-cluster1
  # AWS 서울 리전 지정
  region: ap-northeast-2

# OIDC(OpenID Connect) Identity Provider 설정
iam:
  withOIDC: true  # OIDC 인증 활성화

# EKS 관리형 노드 그룹 설정
managedNodeGroups:
  - name: ng-1  # 노드 그룹 이름
    instanceType: t3.medium  # EC2 인스턴스 타입
    desiredCapacity: 2  # 희망하는 노드 수
    minSize: 2  # 오토스케일링 최소 노드 수
    maxSize: 4  # 오토스케일링 최대 노드 수