# overlays/prod/deployment-patch.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
spec:
  # Production 환경을 위한 높은 가용성 설정
  replicas: 3
  template:
    spec:
      containers:
        - name: pod-container
          # Production 환경 변수 설정
          env:
            - name: CURRENT_ENV
              value: "prod"
          # Production 환경 리소스 설정 (더 높은 리소스 할당)
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"