# /base/services.yml
apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service
  labels:
    app: eks-demo
    release: prometheus
spec:
  # 서비스 타입 명시적 지정
  type: ClusterIP
  # Pod 선택을 위한 라벨 매칭
  selector:
    app: eks-demo
  ports:
    - name: web
      port: 8080
      targetPort: web
      protocol: TCP